import { useEffect, useMemo, useRef, useState } from "react";
import { useOutletContext } from "react-router-dom";
import type { ProductOutletContext } from "./ProductDetail";
import type { UsageExample } from "../types";
import { updateProduct } from "../storage";
import { avroSqlSnippets } from "../utils/avro";
import { openApiCurlSnippets } from "../utils/openapi";
import hljs from "highlight.js/lib/common";
import "highlight.js/styles/github-dark.css";

export default function ProductUsageExamples() {
  const { product } = useOutletContext<ProductOutletContext>();
  const [usageExamples, setUsageExamples] = useState<UsageExample[]>(product.usageExamples || []);
  const [isEditing, setIsEditing] = useState<string | null>(null);
  const [isAdding, setIsAdding] = useState(false);
  const [editDraft, setEditDraft] = useState<UsageExample | null>(null);
  const [newExample, setNewExample] = useState<Omit<UsageExample, 'id'>>({
    name: '',
    description: '',
    code: '',
    language: 'sql'
  });

  // Seed autogenerated examples (one per datasource) into the unified list if missing
  useEffect(() => {
    const autoExamples: UsageExample[] = product.dataSources.map((ds) => {
      const isDataset = ds.kind === "dataset";
      const code = isDataset
        ? avroSqlSnippets(ds.name, ds.schema?.objects || [])[0]?.body || ""
        : openApiCurlSnippets(ds.name, ds.schema?.serverUrl, ds.schema?.firstGetEndpoint)[0]?.body || "";
      return {
        id: `auto_${ds.id}`,
        name: `${ds.name} example`,
        description: "Basic usage example",
        code,
        language: isDataset ? "sql" : "curl",
      } as UsageExample;
    });

    const existsById = new Set((product.usageExamples || []).map((e) => e.id));
    const missing = autoExamples.filter((e) => !existsById.has(e.id));
    if (missing.length > 0) {
      const updated = [...(product.usageExamples || []), ...missing];
      setUsageExamples(updated);
      updateProduct({ ...product, usageExamples: updated, updatedAt: new Date().toISOString() });
    } else if (!usageExamples || usageExamples.length === 0) {
      // ensure local state reflects saved examples
      setUsageExamples(product.usageExamples || []);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [product.id]);

  const handleSaveEdit = () => {
    if (!isEditing || !editDraft) return;
    const updatedExamples = usageExamples.map((ex) => ex.id === isEditing ? editDraft : ex);
    setUsageExamples(updatedExamples);
    const updatedProduct = {
      ...product,
      usageExamples: updatedExamples,
      updatedAt: new Date().toISOString()
    };
    updateProduct(updatedProduct);
    setIsEditing(null);
    setEditDraft(null);
  };

  const handleAdd = () => {
    if (newExample.name.trim() && newExample.description.trim() && newExample.code.trim()) {
      const example: UsageExample = {
        id: crypto.randomUUID(),
        ...newExample
      };
      const updatedExamples = [...usageExamples, example];
      setUsageExamples(updatedExamples);
      
      const updatedProduct = {
        ...product,
        usageExamples: updatedExamples,
        updatedAt: new Date().toISOString()
      };
      updateProduct(updatedProduct);
      
      setNewExample({ name: '', description: '', code: '', language: 'sql' });
      setIsAdding(false);
    }
  };

  const startEditing = (example: UsageExample) => {
    setIsEditing(example.id);
    setEditDraft({ ...example });
  };

  const handleDelete = (id: string) => {
    const updatedExamples = usageExamples.filter(example => example.id !== id);
    setUsageExamples(updatedExamples);
    
    const updatedProduct = {
      ...product,
      usageExamples: updatedExamples,
      updatedAt: new Date().toISOString()
    };
    updateProduct(updatedProduct);
  };

  const getLanguageColor = (language?: string) => {
    switch (language?.toLowerCase()) {
      case 'sql': return 'bg-blue-900/30 text-blue-300 border-blue-800';
      case 'python': return 'bg-green-900/30 text-green-300 border-green-800';
      case 'javascript': return 'bg-yellow-900/30 text-yellow-300 border-yellow-800';
      case 'curl': return 'bg-orange-900/30 text-orange-300 border-orange-800';
      default: return 'bg-gray-900/30 text-gray-300 border-gray-800';
    }
  };

  return (
    <div className="space-y-6">
      <section className="rounded-xl glass">
        <div className="border-b border-zinc-800/60 px-4 py-3 flex items-center justify-between">
          <div className="text-sm font-medium text-white">Usage Examples</div>
          <button
            onClick={() => setIsAdding(true)}
            className="btn-primary text-xs px-3 py-1"
          >
            Add Example
          </button>
        </div>
        
        <div className="p-4 space-y-4">
          {/* Add new example form */}
          {isAdding && (
            <div className="rounded-lg glass p-4 border border-sky-800/50">
              <div className="space-y-3">
                <div>
                  <label className="block text-xs text-zinc-400 mb-1">Name</label>
                  <input
                    type="text"
                    value={newExample.name}
                    onChange={(e) => setNewExample(prev => ({ ...prev, name: e.target.value }))}
                    className="input-glass w-full"
                    placeholder="Enter example name..."
                  />
                </div>
                <div>
                  <label className="block text-xs text-zinc-400 mb-1">Description</label>
                  <textarea
                    value={newExample.description}
                    onChange={(e) => setNewExample(prev => ({ ...prev, description: e.target.value }))}
                    className="input-glass w-full h-16 resize-none"
                    placeholder="Describe what this example demonstrates..."
                  />
                </div>
                <div>
                  <label className="block text-xs text-zinc-400 mb-1">Language</label>
                  <select
                    value={newExample.language}
                    onChange={(e) => setNewExample(prev => ({ ...prev, language: e.target.value }))}
                    className="input-glass w-full"
                  >
                    <option value="sql">SQL</option>
                    <option value="python">Python</option>
                    <option value="javascript">JavaScript</option>
                    <option value="curl">cURL</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-zinc-400 mb-1">Code</label>
                  <textarea
                    value={newExample.code}
                    onChange={(e) => setNewExample(prev => ({ ...prev, code: e.target.value }))}
                    className="input-glass w-full h-32 resize-none font-mono text-xs"
                    placeholder="Enter your code example..."
                  />
                </div>
                <div className="flex gap-2">
                  <button onClick={handleAdd} className="btn-primary text-xs px-3 py-1">
                    Add Example
                  </button>
                  <button 
                    onClick={() => {
                      setIsAdding(false);
                      setNewExample({ name: '', description: '', code: '', language: 'sql' });
                    }}
                    className="btn-ghost text-xs px-3 py-1"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Existing examples (autogenerated + custom) */}
          {usageExamples.length > 0 ? (
            <div className="space-y-4">
              {usageExamples.map((example) => (
                <div key={example.id} className="rounded-lg glass">
                  <div className="border-b border-zinc-800/60 px-4 py-3 flex items-center justify-between">
                    <div>
                      {isEditing === example.id ? (
                        <input
                          type="text"
                          value={editDraft?.name || ''}
                          onChange={(e) => setEditDraft((d) => (d ? { ...d, name: e.target.value } : d))}
                          className="input-glass text-sm font-medium"
                        />
                      ) : (
                        <div className="text-sm font-medium text-white">{example.name}</div>
                      )}
                    </div>
                    <div className="flex gap-2">
                      {isEditing === example.id ? (
                        <>
                          <button
                            onClick={handleSaveEdit}
                            className="btn-primary text-xs px-2 py-1"
                          >
                            Save
                          </button>
                          <button
                            onClick={() => { setIsEditing(null); setEditDraft(null); }}
                            className="btn-ghost text-xs px-2 py-1"
                          >
                            Cancel
                          </button>
                        </>
                      ) : (
                        <>
                          <button
                            onClick={() => startEditing(example)}
                            className="btn-ghost text-xs px-2 py-1"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => {
                              if (confirm('Delete this example?')) {
                                handleDelete(example.id);
                              }
                            }}
                            className="btn-ghost text-rose-300 text-xs px-2 py-1"
                          >
                            Delete
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                  <div className="p-4 space-y-3">
                    {isEditing === example.id ? (
                      <>
                        <div>
                          <label className="block text-xs text-zinc-400 mb-1">Description</label>
                          <textarea
                            value={editDraft?.description || ''}
                            onChange={(e) => setEditDraft((d) => (d ? { ...d, description: e.target.value } : d))}
                            className="input-glass w-full h-16 resize-none"
                          />
                        </div>
                        <div>
                          <label className="block text-xs text-zinc-400 mb-1">Language</label>
                          <select
                            value={editDraft?.language || 'sql'}
                            onChange={(e) => setEditDraft((d) => (d ? { ...d, language: e.target.value } : d))}
                            className="input-glass w-32"
                          >
                            <option value="sql">SQL</option>
                            <option value="python">Python</option>
                            <option value="javascript">JavaScript</option>
                            <option value="curl">cURL</option>
                            <option value="other">Other</option>
                          </select>
                        </div>
                        <div>
                          <label className="block text-xs text-zinc-400 mb-1">Code</label>
                          <textarea
                            value={editDraft?.code || ''}
                            onChange={(e) => setEditDraft((d) => (d ? { ...d, code: e.target.value } : d))}
                            className="input-glass w-full h-32 resize-none font-mono text-xs"
                          />
                        </div>
                      </>
                    ) : (
                      <UsageExampleView
                        example={example}
                        languageColorClass={getLanguageColor(example.language)}
                      />
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            !isAdding && (
              <div className="text-center py-8">
                <div className="text-sm text-zinc-400">No custom usage examples yet.</div>
                <button
                  onClick={() => setIsAdding(true)}
                  className="btn-primary text-xs px-3 py-1 mt-3"
                >
                  Add First Example
                </button>
              </div>
            )
          )}
        </div>
      </section>
    </div>
  );
}

function CodeBlock({ code, language }: { code: string; language?: string }) {
  const codeElementRef = useRef<HTMLElement | null>(null);

  // Map our UI language values to highlight.js language keys
  const mapLanguageToHljs = (lang?: string) => {
    const normalized = (lang || "").toLowerCase();
    switch (normalized) {
      case "js":
      case "javascript":
        return "javascript";
      case "ts":
      case "typescript":
        return "typescript";
      case "py":
      case "python":
        return "python";
      case "sql":
        return "sql";
      case "bash":
      case "sh":
      case "shell":
      case "curl":
        return "bash";
      case "json":
        return "json";
      default:
        return "plaintext";
    }
  };

  useEffect(() => {
    if (codeElementRef.current) {
      hljs.highlightElement(codeElementRef.current);
    }
  }, [code, language]);

  const hljsLanguageClass = `language-${mapLanguageToHljs(language)}`;

  return (
    <div className="code-block rounded-md overflow-hidden">
      <pre className="w-full m-0 p-3 text-xs text-zinc-200 font-mono overflow-auto">
        <code ref={codeElementRef} className={hljsLanguageClass}>
          {code}
        </code>
      </pre>
    </div>
  );
}

function UsageExampleView({
  example,
  languageColorClass,
}: {
  example: UsageExample;
  languageColorClass: string;
}) {
  const [copied, setCopied] = useState(false);
  const [isRunning, setIsRunning] = useState(false);
  const [response, setResponse] = useState<string | null>(null);

  const languageLabel = useMemo(() => example.language?.toUpperCase() || "PLAINTEXT", [example.language]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(example.code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      // no-op
    }
  };

  const handleRun = async () => {
    setIsRunning(true);
    // Simulate latency
    await new Promise((r) => setTimeout(r, 400));
    const mock = generateMockResponse(example);
    setResponse(mock);
    setIsRunning(false);
  };

  return (
    <>
      <p className="text-sm text-zinc-300">{example.description}</p>
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <span className="text-xs text-zinc-400">Language:</span>
          <span className={`rounded-md px-2 py-1 text-xs border ${languageColorClass}`}>
            {languageLabel}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleCopy} className="btn-ghost text-xs px-2 py-1" title="Copy code">
            <span className="inline-flex items-center gap-1">
              <CopyIcon />
              {copied ? "Copied" : "Copy"}
            </span>
          </button>
          <button onClick={handleRun} className="btn-primary text-xs px-2 py-1" title="Run example" disabled={isRunning}>
            <span className="inline-flex items-center gap-1">
              <PlayIcon spinning={isRunning} />
              {isRunning ? "Running" : "Run"}
            </span>
          </button>
        </div>
      </div>
      <CodeBlock code={example.code} language={example.language} />
      {isRunning && (
        <div className="mt-3">
          <div className="mb-1 text-xs text-zinc-400">Mock Response</div>
          <div className="code-block rounded-md overflow-hidden">
            <div className="progress-track">
              <div className="progress-indicator" />
            </div>
            <div className="p-3 space-y-2">
              <div className="h-3 bg-zinc-800 rounded animate-pulse" />
              <div className="h-3 bg-zinc-800 rounded animate-pulse w-5/6" />
              <div className="h-3 bg-zinc-800 rounded animate-pulse w-4/6" />
              <div className="h-3 bg-zinc-800 rounded animate-pulse w-3/6" />
            </div>
          </div>
        </div>
      )}
      {!isRunning && response && (
        <div className="mt-3">
          <div className="mb-1 text-xs text-zinc-400">Mock Response</div>
          <CodeBlock code={response} language="json" />
        </div>
      )}
    </>
  );
}

function CopyIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      className="w-4 h-4"
    >
      <path d="M16 1H6a2 2 0 0 0-2 2v10h2V3h10V1zm3 4H10a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2zm0 14H10V7h9v12z" />
    </svg>
  );
}

function PlayIcon({ spinning }: { spinning?: boolean }) {
  return (
    <span className={`inline-flex items-center ${spinning ? 'animate-pulse' : ''}`}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        className="w-4 h-4 mr-0.5"
      >
        <path d="M8 5v14l11-7L8 5z" />
      </svg>
    </span>
  );
}

function generateMockResponse(example: UsageExample): string {
  const language = (example.language || '').toLowerCase();
  if (language === 'sql') {
    const table = extractTableFromSql(example.code);
    const rows = generateRowsForTable(table, 3);
    return JSON.stringify(rows, null, 2);
  }
  if (language === 'curl' || language === 'bash' || language === 'shell') {
    const payload = {
      status: 200,
      data: {
        id: "acct_123",
        customer_id: "cust_456",
        balance: 1024.55,
        currency: "USD",
      },
      meta: { request_id: "req_abc" },
    };
    return JSON.stringify(payload, null, 2);
  }
  if (language === 'python' || language === 'javascript' || language === 'ts' || language === 'typescript') {
    return JSON.stringify({ result: "Success", items: [1, 2, 3] }, null, 2);
  }
  return JSON.stringify({ output: "Example executed.", length: example.code.length }, null, 2);
}

function extractTableFromSql(sql: string): string | null {
  // naive FROM <table> parser
  const match = sql.match(/from\s+([a-zA-Z0-9_.-]+)/i);
  return match ? match[1] : null;
}

function generateRowsForTable(table: string | null, count: number): Array<Record<string, unknown>> {
  const fields = inferFieldsFromTableName(table);
  const rows: Array<Record<string, unknown>> = [];
  for (let i = 0; i < count; i++) {
    const row: Record<string, unknown> = {};
    for (const f of fields) {
      row[f] = sampleValueForField(f, i);
    }
    rows.push(row);
  }
  return rows;
}

function inferFieldsFromTableName(table: string | null): string[] {
  if (!table) return ["id", "name", "value"];
  if (table.includes("transaction")) return ["transaction_id", "account_id", "amount", "currency", "timestamp"];
  if (table.includes("account")) return ["account_id", "customer_id", "balance", "currency", "opened_at"];
  if (table.includes("customer")) return ["customer_id", "first_name", "last_name", "email", "created_at"];
  return ["id", "name", "value"];
}

function sampleValueForField(field: string, i: number): unknown {
  const now = new Date().toISOString();
  if (field.includes("id")) return `${field.slice(0, 3)}_${1000 + i}`;
  if (field.includes("amount") || field.includes("balance")) return Number((Math.random() * 1000).toFixed(2));
  if (field.includes("currency")) return "USD";
  if (field.includes("first_name")) return ["Alex", "Sam", "Jordan"][i % 3];
  if (field.includes("last_name")) return ["Chen", "Singh", "Garcia"][i % 3];
  if (field.includes("email")) return `user${i}@example.com`;
  if (field.includes("opened") || field.includes("created") || field.includes("timestamp")) return now;
  if (field.includes("name")) return `Item ${i + 1}`;
  if (field.includes("value")) return i + 1;
  return null;
}
